### PR TITLE
Loosen version requirements to support Phoenix 1.3

### PR DESCRIPTION
**Pull request by andrewbredow**
1.3-pre will support the release version once it's available.

### CODE REVIEW

**Comment by mgwidmann** [comment]
I'm surprised this doesn't work already... We've specified anything `~> 1.2` is that only going to support `1.3` and not the pre-release?

**Comment by andrewbredow** [comment]
I thought so to originally. I did a little digging and it turns out that mix uses `allow_pre: false` by default when matching:

```elixir
iex(4)> Version.match?("1.3.0-rc.1", "~> 1.0 or ~> 1.2", allow_pre: true)
true

# what we're expecting ☝️

# what's happening when running `mix deps.get` 👇

iex(5)> Version.match?("1.3.0-rc.1", "~> 1.0 or ~> 1.2", allow_pre: false)
false
iex(6)> Version.match?("1.3.0-rc.1", "~> 1.0 or ~> 1.3-pre", allow_pre: false)
true
```

**Comment by mgwidmann** [comment]
Can we not leave it as `~> 1.0` with `allow_pre: true` so we won't have to update it for `1.4` later... We had a similar PR for `1.2` 😞

**Comment by andrewbredow** [comment]
[Mix.Deps](https://hexdocs.pm/mix/Mix.Tasks.Deps.html) does not support adding `allow_pre` on a per-dependency basis today...

It looks like our options are:

1. Use the method I have in this PR 
2. Change it to allow any release (including pre, but less than 1.4... since we'll probably want to be able to test that before opening the requirement down the road. I think something like this would work: `      {:phoenix, "~> 1.0-pre and < 1.4.0", optional: true}`
3. Fully loosen the requirement, relying on phoenix_html to enforce the correct requirement for Phoenix. I'll let you weigh in on that, I haven't looked into the ramifications.

I think I'm leaning toward option 2 at this point. Thoughts?

**Comment by mgwidmann** [comment]
Ok sure, lets go with option 2

**Comment by andrewbredow** [comment]
👍  :shipit:

**Comment by mgwidmann** [comment]
Published version `1.6.1`. Thanks!

**Pull request merged**
