### PR TITLE
Relax version requirement to support Phoenix 1.2

### PR DESCRIPTION
**Pull request by britto**
Also removed usage of the deprecated test helper `conn/0` in favor of `build_conn/0`.

### CODE REVIEW

**Comment by britto** [comment]
Looks like the build breaks because `phoenix_pubsub` only supports Elixir 1.2, since it uses multi aliases:

```
warning: the dependency phoenix_pubsub requires Elixir "~> 1.2" but you are running on v1.0.5
Compiled lib/phoenix_pubsub/supervisor.ex
Compiled lib/phoenix_pubsub/local_supervisor.ex

== Compilation error on file lib/phoenix_pubsub/tracker.ex ==
** (SyntaxError) lib/phoenix_pubsub/tracker.ex:97: syntax error before: '{'
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

I got a similar setup for my branch [here](https://semaphoreci.com/britto/scrivener_html/branches/relax-phoenix-dependency/builds/1), only changing the Elixir version from `1.0.5` to `1.2.4`.

**Comment by mgwidmann** [comment]
Hmm ok. Lets bump the minimum Elixir version to 1.2 and I'll release it in another release once phoenix 1.2 drops

**Comment by britto** [comment]
@mgwidmann You're right. I did that a few days ago but forgot to push the changes (1f2125b) 😅.

**Comment by mgwidmann** [comment]
Ok I changed the project settings in semaphore to use elixir 1.2 and it passed. I'll release a 1.1.0 now for this.

**Comment by mgwidmann** [comment]
1.1.0 release is out, will bump again when phoenix 1.2 drops

**Comment by britto** [comment]
Awesome! thanks!

**Pull request merged**
