### PR TITLE
Support Phoenix 1.4

### LINKED ISSUE #77: Update for phoenix 1.4.0
Phoenix 1.4.0 has now released: https://phoenixframework.org/blog/phoenix-1-4-0-released
Hope you update this repo soon :)

### PR DESCRIPTION
**Pull request by mcrumm**
Closes #77

### CODE REVIEW

**Comment by tielur** [comment]
I'd love to see this merged and hex.pm updated 👍

**Comment by whitepaperclip** [comment]
@mgwidmann Can you merge?

**Comment by pierot** [comment]
@mgwidmann any news on this one?

**Comment by mgwidmann** [comment]
Sorry about that! Feel free to ping me on the elixir slack channel if I fall behind.

**Pull request merged**
