### PR TITLE
handle when total_entries == 0

### PR DESCRIPTION
**Pull request by ericsullivan**

### CODE REVIEW

**Comment by mgwidmann** [comment]
What does it currently do without your change? Does it error out?

**Comment by ericsullivan** [comment]
It errors,
```
     ** (ArithmeticError) bad argument in arithmetic expression
     stacktrace:
       (scrivener_html) lib/scrivener/html.ex:193:
Scrivener.HTML.page_number_list/3
       (scrivener_html) lib/scrivener/html.ex:179:
Scrivener.HTML.raw_pagination_links/2
       (scrivener_html) lib/scrivener/html.ex:140:
Scrivener.HTML._pagination_links/2
```

In my phoenix app it was a different error though, but that may have been
due to the version, "scrivener_html": {:hex, :scrivener_html, "1.0.0"},

```
     ** (UndefinedFunctionError) undefined function: nil.__struct__/0
     stacktrace:
       nil.__struct__()
       lib/scrivener/html.ex:132: Scrivener.HTML.name_for/2
       lib/scrivener/html.ex:123: Scrivener.HTML.find_path_fn/2
       lib/scrivener/html.ex:102: Scrivener.HTML.pagination_links/4
```


On Thu, Dec 17, 2015 at 10:19 AM, Matt <notifications@github.com> wrote:

> What does it currently do without your change? Does it error out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgwidmann/scrivener_html/pull/5#issuecomment-165481276>
> .
>



-- 
Eric Sullivan

Annkissam: Mission Driven Systems
www.annkissam.com

One Broadway, 14th Floor
Cambridge, MA 02142


C. 978-376-2543 *preferred
B. 617-401-2480
F. 617-507-5922

**Comment by mgwidmann** [comment]
I'm ok with this for now. But perhaps it'd be better to show something to the user rather than rendering nothing...

**Comment by mgwidmann** [comment]
On second thought, can you make it render an empty `ul`, so that way bootstrap should show something to the user...

**Comment by ericsullivan** [comment]
@mgwidmann Here's a better example of the error. The test will produce this error

```
     ** (UndefinedFunctionError) undefined function: nil.__struct__/0
     stacktrace:
       nil.__struct__()
       (scrivener_html) lib/scrivener/html.ex:132: Scrivener.HTML.name_for/2
       (scrivener_html) lib/scrivener/html.ex:123: Scrivener.HTML.find_path_fn/2
       (scrivener_html) lib/scrivener/html.ex:102: Scrivener.HTML.pagination_links/4
       test/scrivener/html_test.exs:152
```

Which is what I was originally seeing in my phoenix app. I could wrap the pagination_links in a conditional block based on entries being not empty, but I figured others might run into the same issue and thought scrivener_html could handle it. Whether it's the empty ul, a more descriptive error, or nothing, that's up to you. Seeing the error might lead you to a different solution, so let me know what I can do to help

**Comment by mgwidmann** [comment]
Thanks, this helped me pin down the problems with your example!

**Comment by mgwidmann** [comment]
Please give version `1.0.2` a try!

**Comment by ericsullivan** [comment]
Work perfect. Thanks for all your help with this.

**Pull request merged**
