### PR TITLE
Added Semantic UI implementation

### PR DESCRIPTION
**Pull request by mylanconnolly**
I added a Semantic UI implementation for the pagination links.

I didn't add tests since it looks like there's not much bootstrap-specific testing going on, but I would be happy to if you'd rather.

Thanks!

### CODE REVIEW

**Comment by mgwidmann** [comment]
Great!

All the tests currently run through the bootstrap version since its the default, so theres no specific test for it since its implicitly tested in every other test. Think you can add one test that just renders overriding that view style? Just would be easier to maintain for later.

**Comment by mylanconnolly** [comment]
I'll get it added and check back. Thanks!

**Comment by mylanconnolly** [comment]
I added a test for Semantic UI styling of an empty paginator. Please let me know if you'd rather add tests for non-empty ones (although I don't know how necessary that would be).

Thanks again!

**Comment by mgwidmann** [comment]
Great, thanks!

**Comment by mgwidmann** [comment]
Released in v1.0.5, thank you for your contribution.

**Comment by mylanconnolly** [comment]
Cool, glad to help out!

**Pull request merged**
