### PR TITLE
add bulma support

### PR DESCRIPTION
**Pull request by lorenzopagano**
Hi!
I've added [bulma](http://bulma.io/documentation/components/pagination/) support.
All tests are passed!
Bye!

Lorenzo

### CODE REVIEW

**Comment by mgwidmann** [comment]
Awesome! Didn't even know about that one... Would you also update the README to advertise it? (and be sure to fix where it says there are `three` supported frameworks)

**Comment by mgwidmann** [comment]
Ready to merge... Would you mind updating the readme as well?

**Comment by lorenzopagano** [comment]
Yes, but I did not push because the final rendering is not entirely equal to [bulma template](http://bulma.io/documentation/components/pagination/); 
the "previous" button and the "next" button should be outside of the unordered list.
I'm working for fix this problem.

**Comment by mgwidmann** [comment]
Ok, np. Let me know when its ready!

**Comment by mgwidmann** [comment]
This branch has merge conflicts now... Did you get the issue you mentioned fixed now?

**Comment by mgwidmann** [comment]
I'd like to merge this, but I don't know what kind of state it is in, and it has conflicts... If this sits for too long I plan to close this PR.

**Comment by b-murphy** [comment]
@mgwidmann / @lorenzopagano I'm happy to complete or issue a new PR; there is complexity with the variations of the position variations of the Bulma pagination, was going to opt for the centered version described here ~ http://bulma.io/documentation/components/pagination/

let me know.

**Comment by mgwidmann** [comment]
If you'd like to branch off of this PR or submit a completely new one that'd be great. I didn't want to resolve the conflicts myself since I'm not too familiar with that CSS framework.

**Comment by b-murphy** [comment]
@mgwidmann I've issued another PR with the latest version of Bulma on there; take a look and let me know what you think :-)

**Comment by mgwidmann** [comment]
Closing in favor of @b-murphy's PR

**Pull request closed without merging**
